FROM httpd:2.4.60

COPY  index.html /usr/local/apache2/htdocs/index.html
COPY  script.js /usr/local/apache2/htdocs/script.js
COPY  style.css /usr/local/apache2/htdocs/style.css

COPY httpd.conf /usr/local/apache2/conf/httpd.conf

EXPOSE 80