# Generated by Django 5.1.1 on 2024-12-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manipulator', '0002_report_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='name', max_length=100, unique=True),
        ),
    ]
